### ISSUE TITLE
Taxa names are shown as UNKNOWN in latest activity. 

### ISSUE THREAD

**Issue by DonPedro34** [simonrolph/inatcounter#2]
In the latest activity when somebody else leaves an identification to a new observation the taxa name is always UNKNOWN, but the English name is correct.

**Comment by simonrolph** [comment]
Just had a look at it now and the latest activity is completely blank and nothing loads!
![image](https://user-images.githubusercontent.com/17750766/169695911-161fd150-291e-4661-a79e-b83d014f6e19.png)

I will have a look, thanks for raising the issue @DonPedro34 👍

**Comment by simonrolph** [comment]
Seems to be working fine now...
![image](https://user-images.githubusercontent.com/17750766/178962571-37db7501-4299-408f-ba8d-6e8ed7a868ec.png)

Will close issue for now
